
(defun second-wait (seconds)
  (interactive)
  (message "-----   3   -----")
  (sleep-for 1)
  (message "-----   2   -----")
  (sleep-for 1)
  (message "-----   1   -----")
  (sleep-for 1)
  (message "----- start -----")
  (sleep-for seconds)
  (message "STOP"))
(defun wait-looper ()
  (interactive)
  (second-wait 7)
  (sleep-for 10)
  (second-wait 7)
  (sleep-for 10)
  (second-wait 7)
  (sleep-for 10)
  (second-wait 7)
  (sleep-for 10)
  (second-wait 7)
  (sleep-for 10))

(global-set-key (kbd "C-<f7>") 'wait-looper)
